export const WORKSPACE_FILE_SEARCH_LIMIT = 50;
export const WORKSPACE_FILE_SEARCH_MAX_SECONDS = 2.5;
export const WORKSPACE_FILE_SEARCH_BUDGET_HINT = `最多返回 ${WORKSPACE_FILE_SEARCH_LIMIT} 项 · 最多搜索 ${WORKSPACE_FILE_SEARCH_MAX_SECONDS} 秒`;
